name: Publish Release

permissions:
    contents: write

on:
    push:
      branches: [ main ]
      paths:
        - "Flow.Launcher.Plugin.Rip/plugin.json"
      tags:
        - "v*"
    workflow_dispatch:
  
jobs:
    publish:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '7.0.x'

            - name: get version
              id: version
              uses: notiz-dev/github-action-json-property@release
              with:
                path: "Flow.Launcher.Plugin.Rip/plugin.json"
                prop_path: "Version"
                
            - run: echo ${{steps.version.outputs.prop}}

            - name: Restore dependencies
              run: |
                cd Flow.Launcher.Plugin.Rip
                dotnet restore

            - name: Build
              shell: pwsh
              run: ./release.ps1

            - name: Publish
              uses: softprops/action-gh-release@v1
              if: success()
              with:
                name: rip v${{ steps.version.outputs.prop }}
                body: ${{ steps.version.outputs.prop }}
                files: "Flow.Launcher.Plugin.Rip/bin/Flow.Launcher.Plugin.Rip.zip"
                tag_name: "v${{ steps.version.outputs.prop }}"
                
